.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

chore: Add GitHub templates

---

.github/pull_request_template.md
config/argocd/templates/argocd.yaml
config/cloudpaks/cp4aiops/resources/templates/05-installation.yaml
config/cloudpaks/cp4aiops/resources/values.yaml

Closes: #19 
- Add remaining sections of the `Installation` CR, declaring all storage classes

fix: Add AIOps storage classes

---

config/cloudpaks/cp4aiops/operators/templates/07-operators/99-postsync-check-all-csvs.yaml
config/cloudpaks/cp4aiops/resources/templates/99-postsync-check-evt-group.yaml

Contributes to: #18 
- Waits for documented conditions of readiness for operators and resources

chore: Add AIOps post sync

---

config/cloudpaks/cp4i/operators/templates/04-operators/00-prereqs/9999-configure-network-policy.yaml
config/cloudpaks/cp4i/operators/templates/04-operators/99-postsync-check-all-csvs.yaml

Closes: #22
- Add postsync job to check for state of CSV resources in the target namespaces where the cp4i-operator application adds subscriptions.
- Adding presync for prereq to potential fix to network ingress, which blocks deployments in some cloud providers
Output of `argocd app list` command or screenshot of the ArgoCD Application synchronization window showing successful application of changes in this branch:
(Note that cp4i-resources was still progressing when I ran this command, but there were no changes made to that application)
```
argocd app list -l app.kubernetes.io/instance=cp4i-app
NAME            CLUSTER                         NAMESPACE      PROJECT  STATUS  HEALTH       SYNCPOLICY  CONDITIONS  REPO                                        PATH …
```

chore: Add synchronization for CP4I

---

config/rhacm/seeds/templates/0100-rhacm-subscription.yaml

Contributes to: #36
- Use subscription channel 2.4
```
NAME                    CLUSTER                         NAMESPACE         PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                               TARGET
argo-app                https://kubernetes.default.svc  openshift-gitops  default  Synced     Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd                                      main
cicd-app                https://kubernetes.default.svc  cicd              default  Synced …
```

chore: Use latest RHACM channel

---

config/cloudpaks/cp4d/install-cognos/templates/resources/cognos.yaml
config/cloudpaks/cp4d/install-dv/templates/resources/dv-service.yaml
config/cloudpaks/cp4d/install-wkc/templates/resources/wkc.yaml
config/cloudpaks/cp4d/install-wos/templates/resources/wos.yaml
config/cloudpaks/cp4d/install-wsl/templates/resources/wsl.yaml

Contributes to: #76 
- Stop hard-coding versions of CP4D operands, letting the operator default to the latest version.
```
NAME                 CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                    TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd-ga                        76-cp4d-update
cp-shared-app …
```

chore: remove hardcoded CP4D operand versions

---

config/argocd-cloudpaks/cp4d/values.yaml

Contributes to: #69
- Change default modules

Change CP4D defaults to use most common features

---

config/argocd-cloudpaks/cp-shared/templates/00-presync-common-config-map.yaml
config/argocd-cloudpaks/cp-shared/templates/00-presync-cp4a-config-map.yaml

Closes: #88
- Adding second preference, for Ceph storage classes

chore: Fallback preference to Ceph storage classes

---

config/cloudpaks/cp4d/install-cognos/Chart.yaml
config/cloudpaks/cp4d/install-cognos/templates/resources/cognos.yaml
config/cloudpaks/cp4d/install-dv/Chart.yaml
config/cloudpaks/cp4d/install-platform/Chart.yaml
config/cloudpaks/cp4d/install-rstudio/Chart.yaml
config/cloudpaks/cp4d/install-wkc/Chart.yaml
config/cloudpaks/cp4d/install-wml/Chart.yaml
config/cloudpaks/cp4d/install-wos/Chart.yaml
config/cloudpaks/cp4d/install-wos/templates/operators/subscription.yaml
config/cloudpaks/cp4d/install-wos/templates/resources/wos.yaml
config/cloudpaks/cp4d/install-wsl/Chart.yaml

Closes: #108
- Update CP4D operand versions
```
NAME                 CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                    TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd                           108-update-cp4d
cp-shared-app        https://kubernetes.default.svc  ibm-cloudpaks     default  Synced  Healthy  Auto-Prune  <none> …
```

chore: Update CP4D operands

---

.github/workflows/lint.yml
.github/workflows/merge-pr.yml
.github/workflows/test-pr.yml
tests/descriptors/operators/gitops-operators.yaml
tests/postbuild/cluster.sh
tests/postbuild/common.sh
tests/postbuild/create-ocs-storageclass.sh
tests/postbuild/gitops.sh
tests/postbuild/test.sh

Contributes to: #107
- New GitHub actions for PR being open and closed
- New scripts to process the actions
Validation run: https://github.com/IBM/cloudpak-gitops/actions/runs/1931100833

chore: Test changes to GitOps repo using OCP cluster

---

.github/workflows/lint.yml
.github/workflows/merge-pr.yml
.github/workflows/test-pr.yml
tests/postbuild/cluster.sh
tests/postbuild/common.sh
tests/postbuild/test.sh
tests/prebuild/lint.sh

Contributes to: #112 
- Instrument testing code to default to not setting up a global pull secret.

feat: Make global pull secret optional

---

.github/workflows/close-pr.yml
.github/workflows/lint.yml
.github/workflows/merge-pr.yml
.github/workflows/test-pr.yml
tests/postbuild/calc-settings.sh

Contributes to: #107 
- Uses commit SHA instead of branch name to calculate release differences.

chore: Avoid dependency on branch existence

---

config/argocd-cloudpaks/cp-shared/templates/00-presync-cp4s-config-map.yaml
config/argocd-cloudpaks/cp-shared/values.yaml
config/argocd-cloudpaks/cp4s/.helmignore
config/argocd-cloudpaks/cp4s/Chart.yaml
config/argocd-cloudpaks/cp4s/templates/00-presync-adjust-parameters.yaml
config/argocd-cloudpaks/cp4s/templates/cp4s-all-app.yaml
config/argocd-cloudpaks/cp4s/templates/cp4s-app.yaml
config/argocd-cloudpaks/cp4s/values.yaml
config/argocd/templates/argocd.yaml
config/cloudpaks/cp4s/install/.helmignore
config/cloudpaks/cp4s/install/Chart.yaml
config/cloudpaks/cp4s/install/templates/prereqs/000-serverless-namespace.yaml
config/cloudpaks/cp4s/install/templates/prereqs/001-cp4s-namespace.yaml
config/cloudpaks/cp4s/install/templates/prereqs/020-cp4s-role.yaml
config/cloudpaks/cp4s/install/templates/prereqs/030-argocd-role-binding-admin.yaml
config/cloudpaks/cp4s/install/templates/prereqs/040-serverless-operator-group.yaml
config/cloudpaks/cp4s/install/templates/prereqs/050-serverless-subscription.yaml
config/cloudpaks/cp4s/install/templates/prereqs/060-knative-serving.yaml
config/cloudpaks/cp4s/install/templates/resources/100-sync-prereqs.yaml
config/cloudpaks/cp4s/install/templates/resources/200-cp4s-threat-mgmt.yaml
config/cloudpaks/cp4s/install/templates/resources/220-openldap.yaml
config/cloudpaks/cp4s/install/templates/subscriptions/050-cp4s-operator-group.yaml
config/cloudpaks/cp4s/install/templates/subscriptions/100-subscription.yaml
config/cloudpaks/cp4s/install/values.yaml
tests/postbuild/cluster.sh
tests/postbuild/create-ocs-storageclass.sh
tests/prebuild/yamllint-config.yaml

Contributes to: #125
- Initial implementation of Cloud Pak for Security

feat: Cloud Pak for Security

---

.github/workflows/merge-pr.yml
config/rhacm/cloudpaks/Chart.yaml
config/rhacm/cloudpaks/templates/placement-argocd.yaml
config/rhacm/cloudpaks/templates/placement-cloudpaks.yaml
config/rhacm/cloudpaks/templates/placement-cp-shared.yaml
config/rhacm/cloudpaks/templates/policy-cp4s.yaml
tests/postbuild/calc-settings.sh
tests/postbuild/gitops.sh

Closes: #125
- Policy, placement rule and policy bindings
- Augment test suite to also deploy RHACM

feat: Add RHACM policy and bindings for Cloud Pak for Security

---

config/cloudpaks/cp4d/install-cognos/Chart.yaml
config/cloudpaks/cp4d/install-cognos/templates/resources/cognos.yaml
config/cloudpaks/cp4d/install-dv/Chart.yaml
config/cloudpaks/cp4d/install-dv/templates/resources/dv-service.yaml
config/cloudpaks/cp4d/install-platform/Chart.yaml
config/cloudpaks/cp4d/install-rstudio/Chart.yaml
config/cloudpaks/cp4d/install-wkc/Chart.yaml
config/cloudpaks/cp4d/install-wml/Chart.yaml
config/cloudpaks/cp4d/install-wos/Chart.yaml
config/cloudpaks/cp4d/install-wos/templates/resources/wos.yaml
config/cloudpaks/cp4d/install-wsl/Chart.yaml
tests/postbuild/cluster.sh
tests/postbuild/create-ocs-storageclass.sh
tests/postbuild/gitops.sh

Closes: #409
- Bump all versions to match the latest patch numbers.

chore: Update CP4D to 4.0.9

---

config/argocd-cloudpaks/cp4aiops/templates/130-cp4aiops-ia-app.yaml
config/argocd/templates/0200-argocd.yaml
config/cloudpaks/cp4aiops/install-aimgr/templates/resources/010-presync-patch-iaf.yaml
config/cloudpaks/cp4aiops/install-ia/.helmignore
config/cloudpaks/cp4aiops/install-ia/Chart.yaml
config/cloudpaks/cp4aiops/install-ia/templates/resources/000-presync-adjust-parameters.yaml
config/cloudpaks/cp4aiops/install-ia/templates/resources/200-ia-config.yaml
config/cloudpaks/cp4aiops/install-ia/templates/subscriptions/020-argocd-role.yaml
config/cloudpaks/cp4aiops/install-ia/templates/subscriptions/021-argocd-role-binding.yaml
config/cloudpaks/cp4aiops/install-ia/templates/subscriptions/100-subscription.yaml
config/cloudpaks/cp4aiops/install-ia/values.yaml
tests/prebuild/yamllint-config.yaml

Contributes to: #157
- Add module for Infrastructure Automation
```
argocd app list --selector app.kubernetes.io/instance=cp4aiops-app 
NAME            CLUSTER                         NAMESPACE      PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                     TARGET
cp4aiops-aimgr  https://kubernetes.default.svc  cp4aiops       default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/cloudpaks/cp4aiops/install-aimgr  157-aiops-af
cp4aiops-app    https://kubernetes.default.svc  cp4aiops       default …
```

feat: WAIOps Infrastructure Automation

---

config/rhacm/seeds/Chart.yaml
config/rhacm/seeds/templates/0100-rhacm-subscription.yaml

Contributes to: #159
- Upgrade subscription channel

chore: Upgrade RHACM to version 2.5

---

config/cloudpaks/cp4aiops/install-aimgr/Chart.yaml
config/cloudpaks/cp4aiops/install-aimgr/templates/subscriptions/100-subscription.yaml
config/cloudpaks/cp4aiops/install-emgr/Chart.yaml
config/cloudpaks/cp4aiops/install-emgr/templates/subscriptions/100-subscription.yaml
config/cloudpaks/cp4aiops/install-ia/Chart.yaml
config/cloudpaks/cp4aiops/install-ia/templates/subscriptions/100-subscription.yaml

Closes: #162
- Update all subscription channels (3.4 for AIManager and IA, 1.8 for Event Manager)
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                     TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                            162-aiops-34
cp-shared-app …
```

chore: Update WAIOps to 3.4

---

config/cloudpaks/cp4aiops/install-emgr/templates/subscriptions/030-sync-prereqs.yaml
config/cloudpaks/cp4aiops/install-emgr/templates/subscriptions/100-subscription.yaml
config/cloudpaks/cp4aiops/install-emgr/values.yaml

Adjust Event Manager versions for WAIOps 3.4.1

---

config/cloudpaks/cp4s/Chart.yaml
config/cloudpaks/cp4s/templates/prereqs/060-knative-serving.yaml
config/cloudpaks/cp4s/templates/subscriptions/100-subscription.yaml

Closes: #165
- Upgrade subscription channel and CR version

chore: Update CP4S to version 1.10

---

config/argocd-cloudpaks/cp4i/Chart.yaml
config/cloudpaks/cp4i/install-apic/Chart.yaml
config/cloudpaks/cp4i/install-apic/templates/0100-subscription-apic.yaml
config/cloudpaks/cp4i/install-apic/templates/0200-api-connect.yaml
config/cloudpaks/cp4i/install-client/Chart.yaml
config/cloudpaks/cp4i/install-mq/Chart.yaml
config/cloudpaks/cp4i/install-mq/templates/0100-subscription-mq.yaml
config/cloudpaks/cp4i/install-mq/templates/0210-queue-manager.yaml
config/cloudpaks/cp4i/install-platform/Chart.yaml
config/cloudpaks/cp4i/install-platform/templates/0100-subscription-platform-navigator.yaml
config/cloudpaks/cp4i/install-platform/templates/0200-platform-navigator.yaml
config/cloudpaks/cp4i/install-prereqs/Chart.yaml
config/cloudpaks/cp4i/install-prereqs/values.yaml

Contributes to: #177
- Update all CP4I CR will latest versions and licenses

chore: Support CP4I 2022.2

---

README.md
config/argocd-cloudpaks/cp4d/Chart.yaml
config/argocd-cloudpaks/cp4d/templates/0100-cp4d-app.yaml
config/argocd-cloudpaks/cp4d/values.yaml
config/cloudpaks/cp4d/Chart.yaml
config/cloudpaks/cp4d/templates/0090-sync-cluster-setup.yaml
config/cloudpaks/cp4d/templates/0100-sync-install-olm.yaml
config/cloudpaks/cp4d/templates/0100-sync-install-platform.yaml
config/cloudpaks/cp4d/templates/0401-postsync-certificates.yaml
config/cloudpaks/cp4d/values.yaml
docs/install.md
tests/postbuild/cluster.sh

Contributes to: #191
- Update CP4D version in Helm charts.

feat: Updates CP4D to 4.6.x

---

README.md
config/argocd-cloudpaks/cp4i/Chart.yaml
config/argocd/templates/0200-argocd.yaml
config/cloudpaks/cp4i/install-apic/Chart.yaml
config/cloudpaks/cp4i/install-apic/templates/0100-subscription-apic.yaml
config/cloudpaks/cp4i/install-apic/templates/0200-api-connect.yaml
config/cloudpaks/cp4i/install-client/Chart.yaml
config/cloudpaks/cp4i/install-mq/Chart.yaml
config/cloudpaks/cp4i/install-mq/templates/0100-subscription-mq.yaml
config/cloudpaks/cp4i/install-mq/templates/0210-queue-manager.yaml
config/cloudpaks/cp4i/install-platform/Chart.yaml
config/cloudpaks/cp4i/install-platform/templates/0100-subscription-platform-navigator.yaml
config/cloudpaks/cp4i/install-platform/templates/0200-platform-navigator.yaml
config/cloudpaks/cp4i/install-prereqs/Chart.yaml
tests/postbuild/cluster.sh

closes: #194
- Update versions and license numbers.
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                    TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                           194-cp4i-2022-4
cp-shared-app …
```

chore: Update version of Cloud Pak for Integration to 2022.4

---

.github/workflows/merge-pr.yml

Contributes to: #issue_number
- <change 1 ... >
- <change 2 ... >

107 release process

---

.github/workflows/merge-pr.yml

Contributes to: #107 
- Using semantic-release package to promote releases

fix: Release promotion process

---

README.md
config/argocd-cloudpaks/cp4waiops/Chart.yaml
config/cloudpaks/cp4waiops/install-aimgr/Chart.yaml
config/cloudpaks/cp4waiops/install-aimgr/templates/subscriptions/100-subscription.yaml
config/cloudpaks/cp4waiops/install-emgr/Chart.yaml
config/cloudpaks/cp4waiops/install-emgr/templates/resources/210-event-manager.yaml
config/cloudpaks/cp4waiops/install-emgr/templates/subscriptions/100-subscription.yaml
config/cloudpaks/cp4waiops/install-emgr/values.yaml
config/cloudpaks/cp4waiops/install-ia/Chart.yaml
config/cloudpaks/cp4waiops/install-ia/templates/subscriptions/100-subscription.yaml

Contributes to: #201
- Updated all subscription channels
- Updated resource versions
- Updated Event Manager `NOI` resource to sort attributes similarly to OLM form builder (easier for cross-release comparisons) and, more importantly, to remove the now deprecated `zen` block.
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                      TARGET
argo-app …
```

feat: Upgrade WAIOps to 3.6.0

---

README.md
config/argocd/templates/0200-argocd.yaml
config/cloudpaks/cp4a/operators/Chart.yaml
config/cloudpaks/cp4a/operators/templates/0110-base-operator.yaml
config/cloudpaks/cp4a/resources/Chart.yaml
config/cloudpaks/cp4a/resources/templates/0201-icp4a-cluster.yaml

closes: #203
- Update subscription and resource versions
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                  TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                         203-cp4ba-2202
cp-shared-app …
```

feat: Upgrade Business Automation to 22.0.2

---

config/argocd-cloudpaks/cp4d/Chart.yaml
config/argocd-cloudpaks/cp4d/values.yaml

closes: #206
- Update CP4D to 4.6.1
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                  TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                         191-cp4d-461
cp-shared-app        https://kubernetes.default.svc …
```

chore: Update CP4D to 4.6.1

---

config/rhacm/seeds/Chart.yaml
config/rhacm/seeds/templates/0100-rhacm-subscription.yaml

Contributes to: #208 
- Upgrade RHACM to 2.7

feat: Upgrade RHACM from 2.6. to 2.7

---

config/argocd-cloudpaks/cp4d/Chart.yaml
config/argocd-cloudpaks/cp4d/values.yaml

Contributes to: #212
- Update CP4D version

fix: Update CP4D to 4.6.2

---

README.md

closes: #215
- Update version in readme. No other changes were required.

fix: Update CP4WAIOps to 3.6.2

---

README.md
config/argocd-cloudpaks/cp-shared/Chart.yaml
config/argocd-cloudpaks/cp-shared/templates/0050-sync-common-config-map.yaml
config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4a-config-map.yaml
config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4s-config-map.yaml

closes: #217 
- Auto-detects NetApp ONTAP storage classes if present in the cluster.

feat: Support NetApp ONTAP storage classes

---

README.md
config/argocd-cloudpaks/cp-shared/templates/0050-sync-common-config-map.yaml
config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4a-config-map.yaml
config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4s-config-map.yaml

contributes-to: #219
- Adjust storage classes for EFS

fix: Adjust detection of storage classes in AWS clusters

---

config/cloudpaks/cp4i/install-prereqs/Chart.yaml
config/cloudpaks/cp4i/install-prereqs/templates/0050-sync-configure-network-policy.yaml
config/cloudpaks/cp4waiops/install-aimgr/Chart.yaml
config/cloudpaks/cp4waiops/install-aimgr/templates/subscriptions/030-sync-prereqs.yaml
config/cloudpaks/cp4waiops/install-emgr/Chart.yaml
config/cloudpaks/cp4waiops/install-emgr/templates/subscriptions/030-sync-prereqs.yaml

Contributes to: #219
- Fix deployment of Cloud Paks in ROSA

fix: Fix deployment of Cloud Paks in ROSA

---

README.md
config/cloudpaks/cp4i/install-apic/Chart.yaml
config/cloudpaks/cp4i/install-apic/templates/0100-subscription-apic.yaml
config/cloudpaks/cp4i/install-apic/templates/0200-api-connect.yaml
config/cloudpaks/cp4i/install-mq/Chart.yaml
config/cloudpaks/cp4i/install-mq/templates/0100-subscription-mq.yaml
config/cloudpaks/cp4i/install-mq/templates/0210-queue-manager.yaml
config/cloudpaks/cp4i/install-platform/Chart.yaml
config/cloudpaks/cp4i/install-platform/templates/0100-subscription-platform-navigator.yaml
config/cloudpaks/cp4i/install-platform/templates/0200-platform-navigator.yaml

closes: #251
- Update operator channels, operand versions, and licensing terms
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                    TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                           251-cp4i-2023-2 …
```

feat: Update Cloud Pak for Integration to version 2023.2.1

---

config/argocd-cloudpaks/cp4d/Chart.yaml
config/argocd-cloudpaks/cp4d/templates/0100-cp4d-app.yaml
config/argocd-cloudpaks/cp4d/templates/0200-cp4d-platform-app.yaml
config/argocd-cloudpaks/cp4d/values.yaml
config/cloudpaks/cp4d/Chart.yaml
config/cloudpaks/cp4d/templates/0402-postsync-integrate-iam.yaml
config/cloudpaks/cp4d/values.yaml

closes: #259
- Add a new post-sync hook to optionally perform IAM integration

feat: Enable IAM integration for Cloud Pak for Data

---

config/rhacm/seeds/Chart.yaml
config/rhacm/seeds/templates/0100-rhacm-subscription.yaml

closes: #255
- Upgrade the version of RHACM

feat: Upgrade RHACM to 2.8

---

README.md

contributes to: #261
- Fix version of WAIOps in README

Update WAIOps version in README.md

---

README.md
config/argocd-cloudpaks/cp4d/Chart.yaml
config/argocd-cloudpaks/cp4d/values.yaml
config/cloudpaks/cp4d/Chart.yaml
config/cloudpaks/cp4d/templates/0090-sync-cluster-setup.yaml
config/cloudpaks/cp4d/templates/0100-sync-install-olm.yaml
config/cloudpaks/cp4d/templates/0100-sync-install-platform.yaml
config/cloudpaks/cp4d/templates/0401-postsync-certificates.yaml
config/cloudpaks/cp4d/templates/0402-postsync-integrate-iam.yaml

closes: #267 
- Update version of CP4D to 4.7.2

fix: Upgrade Cloud Pak for Data 4.7.2

---

README.md
config/argocd-cloudpaks/cp4waiops/Chart.yaml
config/argocd-cloudpaks/cp4waiops/values.yaml
config/cloudpaks/cp4waiops/install-aimgr/Chart.yaml

closes: #269 
- Update README.nd (No changes to install procedure)

fix: Update Cloud Pak for WAIOps to 4.1.2

---

README.md
config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4s-config-map.yaml
config/argocd-cloudpaks/cp4s/templates/00-presync-adjust-parameters.yaml
config/argocd-cloudpaks/cp4s/templates/cp4s-all-app.yaml
config/argocd-cloudpaks/cp4s/templates/cp4s-app.yaml
config/argocd-cloudpaks/cp4s/values.yaml
config/cloudpaks/cp4s/Chart.yaml
config/cloudpaks/cp4s/templates/resources/200-cp4s-threat-mgmt.yaml
config/cloudpaks/cp4s/templates/resources/220-openldap.yaml
config/cloudpaks/cp4s/values.yaml
tests/prebuild/yamllint-config.yaml

closes: #271
- Update version in README.md
- Minor change to `CP4SThreatManagement` CR to match docs

fix: Update Cloud Pak for Security to 1.10.15

---

README.md
config/argocd-cloudpaks/cp-shared/Chart.yaml
config/argocd-cloudpaks/cp-shared/templates/0050-sync-common-service-maps.yaml
config/cloudpaks/cp-shared/operators/templates/0000-cert-manager-namespace.yaml
config/cloudpaks/cp-shared/operators/templates/0100-cert-manager-operator-group.yaml
config/cloudpaks/cp-shared/operators/templates/0100-cert-manager-subscription.yaml
config/cloudpaks/cp-shared/operators/values.yaml
config/cloudpaks/cp4a/operators/Chart.yaml
config/cloudpaks/cp4a/operators/templates/0021-service-accounts-for-demo.yaml
config/cloudpaks/cp4a/operators/templates/0021-service-accounts-scc.yaml
config/cloudpaks/cp4a/operators/templates/0110-base-operator.yaml
config/cloudpaks/cp4a/resources/Chart.yaml
config/cloudpaks/cp4a/resources/templates/0201-icp4a-cluster.yaml

closes: #273
- Minor updates to reflect new subscription channels
- Remove obsolete entries

feat: Update CP4BA version to 23.0.1

---

config/rhacm/seeds/templates/0000-rhacm-users-group-prereq.yaml
config/rhacm/seeds/templates/9000-post-multi-cluster-engine.yaml

- Use multi-arch images for sync hooks
```
NAME                                  CLUSTER                         NAMESPACE                PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                  TARGET
openshift-gitops/argo-app             https://kubernetes.default.svc  openshift-gitops         argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd …
```

feat: Use multi-arch oc client for RHACM install

---

README.md

closes: #315
- List the Cloud Paks that can run on Power arch
- Minor editorial changes

chore: Document hardware support
