IBM/cloudpak-gitops

config/cloudpaks/cp4a/operators/templates/07-operators/99-postsync-check-all-csvs.yaml, config/cloudpaks/cp4i/operators/templates/04-operators/99-postsync-check-all-csvs.yaml
Closes: #24
- Wait for CSVs to succeed after synchronizing the `cp4a-operators` application.
- Applying a small fix to the same sync point in the `cp4i-operators` and `cp4aiops-operators` applications (found while validating this PR)
=> chore: Add synchronization for CP4BA

config/cloudpaks/cp4a/operators/templates/07-operators/base-operator.yaml, config/cloudpaks/cp4a/resources/templates/00-presync-patch-db2-sts.yaml, config/cloudpaks/cp4a/resources/templates/icp4a-cluster.yaml
Contributes to: #26
- Update starting CSV for operators
- Update ICP4ACluster to match default YAML
Clean installation: 
```
argocd app list -l app.kubernetes.io/instance=cp4a-app
NAME            CLUSTER                         NAMESPACE      PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                             TARGET
cp4a-app        https://kubernetes.default.svc  ibm-cloudpaks  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd-cloudpaks/cp4a     26-cp4a-update
cp4a-operators …
```
=> chore: Update CP4BA with 21.0.3 fixpack

config/cloudpaks/cp4aiops/operators/templates/00-prereqs/9999-postsync-close-route.yaml
Closes: #30 
- <change 1 ... >
- <change 2 ... >
Pod logs:
Evidence of new block of code taking the expected approach of not exiting with an error if the route does not exist:
```
W
+ oc get service.serving.knative.dev/kn-cli -n knative-serving
I0923 17:16:30.254180       7 request.go:665] Waited for 1.002146047s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/autosc
aling/v2beta1?timeout=32s
I0923 17:16:40.454247       7 request.go:665] Waited for 11.202048999s due to client-side throttling, not priority and fairness, request: …
```
=> bug: Handle missing kn-cli service

config/cloudpaks/cp4a/resources/templates/icp4a-cluster.yaml
Closes: #26 
- Reverse change to BAA deployment. It should was set to false and should be kept that way. Context: https://www.ibm.com/docs/en/cloud-paks/1.0?topic=hub-advanced-configuration-business-automation-application
```
NAME                    CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                               TARGET
argo-app                https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none> …
```
=> chore: Reverse olm_demo_application change

config/cloudpaks/cp4i/operators/templates/04-operators/mq.yaml, config/cloudpaks/cp4i/operators/templates/04-operators/platform-navigator.yaml, config/cloudpaks/cp4i/resources/templates/05-crds/api-connect.yaml, config/cloudpaks/cp4i/resources/templates/05-crds/platform-navigator.yaml, config/cloudpaks/cp4i/resources/templates/05-crds/queue-manager.yaml, config/cloudpaks/cp4i/resources/values.yaml
Closes: #53
- Updates to channels, versions and license codes.
```
NAME                    CLUSTER                         NAMESPACE         PROJECT  STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                               TARGET
argo-app                https://kubernetes.default.svc  openshift-gitops  default  Synced     Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops      config/argocd-ga                                   53-cp4i-upgrade
cicd-app                https://kubernetes.default.svc  cicd …
```
=> Upgrades CP4I to 2021.3 release

config/cloudpaks/cp4i/client/base/kustomization.yaml, config/cloudpaks/cp4i/client/base/mq-dev-patterns-jms-deployment.yaml, config/cloudpaks/cp4i/client/base/mq-dev-patterns-node-deployment.yaml, config/cloudpaks/cp4i/client/base/sbo-account-role-binding.yaml, config/cloudpaks/cp4i/client/base/service-binding.yaml
Closes: #55
- Minor tweak to resource definition for ServiceBinding resource
- Minor tweaks to pod deployments using the build images (also require a minor change to the source code of the application)
```
NAME                    CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                               TARGET
argo-app                https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops …
```
=> fix: Comply to stable API for SBO

config/cicd/base/02-rolebindings/pipeline-service-role.yaml, docs/install.md
Contributes to: #45
- Tekton Pipelines need another cluster role
- Add missing pull secret to instructions
=> fix: Add missing cluster roles and secrets

config/argocd-cloudpaks/cp-shared/templates/00-presync-common-config-map.yaml, config/argocd-cloudpaks/cp-shared/templates/00-presync-cp4a-config-map.yaml
Closes: #58
- Pod was exiting with error on AWS when not using EFS storage
```
NAME                    CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                               TARGET
argo-app                https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd-ga                                   58-aws-efs
cicd-app                https://kubernetes.default.svc  cicd …
```
=> fix: Auto-detection of EFS on AWS

CONTRIBUTING.md, config/argocd-cloudpaks/cp4a/templates/cp4a-app.yaml, config/argocd-cloudpaks/cp4a/templates/cp4a-operator-app.yaml, config/argocd-cloudpaks/cp4a/templates/cp4a-resources-app.yaml, config/cloudpaks/cp4a/operators/Chart.yaml, config/cloudpaks/cp4a/operators/templates/01-namespaces/individual.yaml, config/cloudpaks/cp4a/operators/templates/07-operators/operator-group.yaml, config/cloudpaks/cp4a/operators/values.yaml, config/cloudpaks/cp4aiops/operators/Chart.yaml, config/cloudpaks/cp4aiops/operators/templates/ai-manager/00-namespaces.yaml, config/cloudpaks/cp4aiops/operators/templates/ai-manager/05-operator-group.yaml, config/cloudpaks/cp4aiops/operators/templates/evt-manager/00-namespaces.yaml, config/cloudpaks/cp4aiops/operators/values.yaml, config/cloudpaks/cp4i/operators/Chart.yaml, config/cloudpaks/cp4i/operators/templates/01-namespaces/individual.yaml, config/cloudpaks/cp4i/operators/templates/04-operators/operator-group.yaml, config/cloudpaks/cp4i/operators/values.yaml, config/rhacm/cloudpaks/Chart.yaml, config/rhacm/cloudpaks/templates/policy-cp4a.yaml, docs/install.md, tests/prebuild/yamllint-config.yaml
Contributes to: #66
- Only create individual Cloud Pak namespaces if different than `ibm-cloudpaks`
```
NAME                    CLUSTER                         NAMESPACE         PROJECT  STATUS     HEALTH       SYNCPOLICY  CONDITIONS  REPO                                        PATH                                               TARGET
argo-app                https://kubernetes.default.svc  openshift-gitops  default  Synced     Healthy      Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd-ga                                   66-fix-ns
cicd-app …
```
=> fix: Create namespaces conditionally

config/argocd-cloudpaks/cp4aiops/templates/cp4aiops-resources-app.yaml
Contributes to: #58 
- Avoid repeat loop due to clusterDomain field in Cloud Pak for AIOps
```
NAME                    CLUSTER                         NAMESPACE         PROJECT  STATUS   HEALTH       SYNCPOLICY  CONDITIONS       REPO                                        PATH                                               TARGET
argo-app                https://kubernetes.default.svc  openshift-gitops  default  Synced   Healthy      Auto-Prune  <none>           https://github.com/IBM/cloudpak-gitops.git  config/argocd-ga                                   66-ignore-aiops-noi
cicd-app …
```
=> fix: Ignore NOI clusterDomain field

config/cloudpaks/cp4aiops/operators/templates/evt-manager/00-namespaces.yaml, config/cloudpaks/cp4aiops/resources/templates/ai-manager/10-ai-manager.yaml, config/cloudpaks/cp4aiops/resources/templates/evt-manager/05-event-manager.yaml, tests/prebuild/yamllint-config.yaml
Contributes to: #58
- Make the namespace for event manager managed in the cp4aiops app
```
NAME                CLUSTER                         NAMESPACE      PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                 TARGET
cp4aiops-app        https://kubernetes.default.svc  ibm-cloudpaks  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd-cloudpaks/cp4aiops     58-fix-evt-mgr
cp4aiops-operators  https://kubernetes.default.svc  ibm-cloudpaks  default  Synced  Healthy  Auto-Prune …
```
=> fix: Event manager namespace is not conditional

config/cloudpaks/cp4aiops/resources/templates/00-presync-adjust-parameters.yaml
Contributes to: #58
- Patch AI Manager with IAF was using the Event Manager namespace and failing
```
NAME                    CLUSTER                         NAMESPACE         PROJECT  STATUS     HEALTH    SYNCPOLICY  CONDITIONS  REPO                                        PATH                                               TARGET
argo-app                https://kubernetes.default.svc  openshift-gitops  default  Synced     Healthy   Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd-ga                                   58-fix-aiops
cicd-app …
```
=> fix: Patch AIManager with IAF

config/rhacm/cloudpaks/templates/placement-argocd.yaml, config/rhacm/cloudpaks/templates/placement-cp-shared.yaml
Contributes to: #73
- Missing placement rule for GitOps matching `cp4d` deployments
=> bug: Missing "cp4d" placement rules

config/cloudpaks/cp4d/install-platform/templates/prereqs/020-operator-group-cs.yaml
Contributes to: #73 
- The new logic stopped creating OperatorGroup regardless of its presence. Fixed it.
=> bug: Create common-services operator group

config/argocd-cloudpaks/cp-shared/templates/00-presync-common-config-map.yaml, config/argocd-cloudpaks/cp-shared/templates/00-presync-cp4a-config-map.yaml
Contributes to: #88
- Detect ODF storage classes before starting considering the target cloud.
```
NAME                 CLUSTER                         NAMESPACE         PROJECT  STATUS     HEALTH       SYNCPOLICY  CONDITIONS  REPO                                        PATH                                  TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  default  Synced     Healthy      Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd-ga                      88-favor-odf-sc
cp-shared-app        https://kubernetes.default.svc …
```
=> feat: Default to ODF storage classes

config/cloudpaks/cp-shared/operators/templates/0050-catalogsource-ibm.yaml, config/cloudpaks/cp4d/install-cognos/templates/resources/cognos.yaml, config/cloudpaks/cp4d/install-wos/templates/resources/wos.yaml
Contributes to: #49
- We found issues where the latest patches for Cloud Paks are not getting reflected in the catalogs labeled with `v1.22`
=> chore: Reverse annotation for Catalog Source in OCP 4.9

README.md, config/cloudpaks/cp4aiops/operators/Chart.yaml, config/cloudpaks/cp4aiops/operators/templates/01-argocd-admin-namespace.yaml, config/cloudpaks/cp4aiops/operators/templates/ai-manager/01-argocd-admin-namespace.yaml, config/cloudpaks/cp4aiops/operators/templates/ai-manager/05-operator-group.yaml, config/cloudpaks/cp4aiops/operators/templates/ai-manager/99-sync-check-all-csvs.yaml, config/cloudpaks/cp4aiops/operators/templates/evt-manager/00-namespaces.yaml, config/cloudpaks/cp4aiops/operators/templates/evt-manager/02-sync-prereqs.yaml, config/cloudpaks/cp4aiops/operators/templates/evt-manager/05-operator-group.yaml, config/cloudpaks/cp4aiops/operators/templates/evt-manager/09-subscription.yaml, config/cloudpaks/cp4aiops/operators/templates/evt-manager/99-sync-check-all-csvs.yaml, config/cloudpaks/cp4aiops/resources/Chart.yaml, config/cloudpaks/cp4aiops/resources/templates/ai-manager/10-ai-manager.yaml, config/cloudpaks/cp4aiops/resources/templates/ai-manager/20-sync-check-ai-readiness.yaml, config/cloudpaks/cp4aiops/resources/templates/ai-manager/99-postsync-certificates.yaml, config/cloudpaks/cp4aiops/resources/templates/evt-manager/05-event-manager.yaml, config/cloudpaks/cp4aiops/resources/templates/evt-manager/20-sync-check-emgr-group.yaml
Closes: #92
- Matches namespace to suggested namespace in Event Manager docs
- Replace `cloudctl`-based installation with OLM-based installation
```
NAME                 CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                  TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd-ga                      92-aiops-evtmgr
cp-shared-app …
```
=>  chore: OLM installation for CP4AIOps Event Manager

config/argocd-cloudpaks/cp4a/templates/00-presync-adjust-ocp-platform.yaml, config/argocd-cloudpaks/cp4a/templates/00-presync-adjust-storage-classes.yaml, config/argocd-cloudpaks/cp4d/templates/00-presync-adjust-storage-classes.yaml, config/argocd-cloudpaks/cp4i/templates/00-presync-adjust-storage-classes.yaml, config/cloudpaks/cp4aiops/resources/templates/00-presync-adjust-parameters.yaml, config/cloudpaks/cp4d/install-wkc/templates/operators/00-presync-set-kernel-param.yaml
Contributes to: #84 
- Removes dead code for RH OpenShift GitOps preview from sync hooks
=> chore: Remove dead code for GitOps preview

config/argocd-cloudpaks/cp4aiops/Chart.yaml, config/argocd-cloudpaks/cp4aiops/templates/cp4aiops-resources-app.yaml, config/cloudpaks/cp4aiops/operators/Chart.yaml, config/cloudpaks/cp4aiops/operators/templates/ai-manager/02-sync-prereqs.yaml, config/cloudpaks/cp4aiops/operators/templates/evt-manager/02-sync-prereqs.yaml, config/cloudpaks/cp4aiops/resources/Chart.yaml, config/cloudpaks/cp4aiops/resources/templates/ai-manager/15-patch-orchestrator.yaml, config/cloudpaks/cp4aiops/resources/templates/ai-manager/20-sync-check-ai-readiness.yaml, docs/install.md, docs/rhacm.md
Closes: #98
- Include all pre-installation steps for dealing with entitlement secrets
```
NAME                 CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                  TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd                         98-aiops-aimgr
cp-shared-app        https://kubernetes.default.svc  ibm-cloudpaks     default …
```
=> bug: Add missing AIOps resources

config/argocd-cloudpaks/cp4a/Chart.yaml, config/argocd-cloudpaks/cp4a/templates/cp4a-app.yaml, config/argocd-cloudpaks/cp4a/templates/cp4a-resources-app.yaml, config/argocd-cloudpaks/cp4a/values.yaml, config/cloudpaks/cp4a/resources/Chart.yaml, config/cloudpaks/cp4a/resources/values.yaml
Contributes to: #101
- Adding block storage parameter to Argo applications. Without the parameter, Argo keeps deleting the respective value from the application.
```
NAME                 CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                  TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops.git  config/argocd                         104-fix-cp4a-helm …
```
=> fix: Add missing storage parameters on Cloud Pak for Business Automation

config/argocd-cloudpaks/cp4i/Chart.yaml, config/argocd-cloudpaks/cp4i/templates/cp4i-operator-app.yaml, config/argocd-cloudpaks/cp4i/templates/cp4i-resources-app.yaml, config/cloudpaks/cp4i/operators/Chart.yaml, config/cloudpaks/cp4i/operators/templates/02-rolebinding/20-role-binding.yaml, config/cloudpaks/cp4i/operators/templates/02-rolebinding/20-role.yaml, config/cloudpaks/cp4i/operators/templates/04-operators/0100-sync-prereqs.yaml, config/cloudpaks/cp4i/operators/templates/04-operators/0110-platform-navigator.yaml, config/cloudpaks/cp4i/operators/templates/04-operators/0120-sync-check-all-csvs.yaml, tests/postbuild/common.sh, tests/postbuild/test.sh
Contributes to: #112
- Add pre-synchronization hook to populate the entitlement key for the Entitled Registry to the target namespace.
=> chore: Use namespace-scoped pull secrets for CP4I

.github/workflows/merge-pr.yml, tests/postbuild/promote-release.sh
Contributes to: #107
- Remove needless checkout of source branch during promotion
- Fix "close" action
=> fix: Promote release even if source branch is deleted

.github/workflows/test-pr.yml, config/cloudpaks/cp4aiops/install-aimgr/Chart.yaml, config/cloudpaks/cp4aiops/install-aimgr/templates/resources/30-sync-certificates.yaml, config/cloudpaks/cp4aiops/install-emgr/Chart.yaml, tests/postbuild/calc-settings.sh, tests/postbuild/gitops.sh
Closes:#122
- Adjusted setting of ingress certificate to be a Sync rather than PostSync step.
```
2022-03-09T14:08:21+0000: INFO: Synchronization of cp4aiops-app complete.
Name:               cp4aiops-app
Project:            default
Server:             https://kubernetes.default.svc/
Namespace:          cp4aiops
URL:                https://openshift-gitops-server-openshift-gitops.gitops-122-cp4aiops-321-1e3af63cfd19e855098d645120e18baf-0000.us-south.containers.appdomain.cloud/applications/cp4aiops-app
Repo:               https://github.com/IBM/cloudpak-gitops
Target:             122-cp4aiops-321
Path: …
```
=> chore: Upgrade WAIOps to 3.2.1

config/cloudpaks/cp4s/Chart.yaml, config/cloudpaks/cp4s/templates/prereqs/020-cloudpaks-role.yaml, config/cloudpaks/cp4s/templates/resources/220-openldap.yaml
Closes: #140
- Missing post-install peermissions for the installer service account
=> chore: Fix roles for OpenLDAP setup

docs/rhacm.md
Contributes to: #142
The instructions are missing the assignment of the `gitops_url` and `gitops_branch` variables.
=> Fix RHACM documentation

config/argocd-cloudpaks/cp4i/Chart.yaml, config/argocd-cloudpaks/cp4i/templates/0200-cp4i-prereqs-app.yaml, tests/postbuild/gitops.sh
Contributes to: #147
- Retries the synchronization of `cp4i-prereqs` for a bit longer to give time for the `ibm-entitlement-key` to be copied to the Cloud Pak namespace.
- Small reordering of steps in the test script to set Argo server settings before installing the Cloud Pak, so that it is easier to get to the Argo CD console before the pipeline completely ends its run.
=> fix: Add retries to CP4I apps

config/cloudpaks/cp4i/install-prereqs/values.yaml, config/rhacm/cloudpaks/Chart.yaml, config/rhacm/cloudpaks/templates/policy-cp-shared.yaml, config/rhacm/cloudpaks/templates/policy-cp4a.yaml, config/rhacm/cloudpaks/templates/policy-cp4aiops.yaml, config/rhacm/cloudpaks/templates/policy-cp4d.yaml, config/rhacm/cloudpaks/templates/policy-cp4i.yaml, config/rhacm/cloudpaks/templates/policy-cp4s.yaml, tests/prebuild/lint.sh
Contributes to: #154
- Modify all RHACM policies to require the existence of the ibm-entitlement-key in the openshift-gitops namespace.
Verification:
Notice how RHACM does not apply the policies for the Cloud Paks when the key is missing:
Details from one of the examples:
=> chore: Use entitlement key as a gate for Cloud Pak policies on RHACM

config/cloudpaks/cp4s/Chart.yaml, config/cloudpaks/cp4s/templates/resources/220-openldap.yaml
Closes: #167 
- Per [new instructions](https://www.ibm.com/docs/en/cloud-paks/cp-security/1.10?topic=support-installing-cpctl-utility-access-actions), replace `oc cp` with `rsync...`.
```
argocd app get cp4s-app
Name:               cp4s-app
Project:            default
Server:             https://kubernetes.default.svc/
Namespace:          openshift-gitops
URL:                https://openshift-gitops-server-openshift-gitops.gitops-167-cp4s-timeout-1e3af63cfd19e855098d645120e18baf-0000.us-south.containers.appdomain.cloud/applications/cp4s-app
Repo:               https://github.com/IBM/cloudpak-gitops
Target: …
```
=> fix: cpctl download timeout on ROKS

config/argocd-rhacm/Chart.yaml, config/argocd-rhacm/templates/rhacm-seeds-app.yaml, config/argocd/Chart.yaml, config/argocd/templates/0200-argocd.yaml, config/argocd/templates/0300-app-project-rhacm-control-plane.yaml, config/rhacm/seeds/Chart.yaml, config/rhacm/seeds/templates/0000-namespace-rhacm-creds.yaml, config/rhacm/seeds/templates/0000-rhacm-users-group-prereq.yaml, config/rhacm/seeds/templates/0020-argocd-roles.yaml, config/rhacm/seeds/templates/0020-rhacm-users-creds-roles.yaml, config/rhacm/seeds/templates/0030-argocd-role-bindings.yaml, config/rhacm/seeds/templates/0030-rhacm-users-creds-bindings.yaml, config/rhacm/seeds/values.yaml, docs/rhacm.md
Closes: #169
- Create access group, roles, and role-bindings for non-superadmin RHACM users
```
NAME                 CLUSTER                         NAMESPACE                PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                  TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops         argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                         169-rhacm-roles
cp-shared-app …
```
=> feat: RHACM non-admin users

config/rhacm/seeds/Chart.yaml, config/rhacm/seeds/templates/0100-rhacm-subscription.yaml, tests/postbuild/cluster.sh
Closes: #171
- Update RHACM from 2.5 to 2.6
=> chore: Upgrade RHACM from 2.5 to 2.6

config/cloudpaks/cp4aiops/install-aimgr/Chart.yaml, config/cloudpaks/cp4aiops/install-aimgr/templates/subscriptions/100-subscription.yaml, config/cloudpaks/cp4aiops/install-emgr/Chart.yaml, config/cloudpaks/cp4aiops/install-emgr/templates/subscriptions/100-subscription.yaml, config/cloudpaks/cp4aiops/install-emgr/values.yaml, config/cloudpaks/cp4aiops/install-ia/Chart.yaml, config/cloudpaks/cp4aiops/install-ia/templates/subscriptions/100-subscription.yaml
Contributes to: #180
- Bump up all subscription channels for WAIOps components
Output of AI Manager verification:
```
oc get installations.orchestrator.aiops.ibm.com -A && echo "" &&  oc get ircore,AIOpsAnalyticsOrchestrator,lifecycleservice -A -o custom-columns="KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,STATUS:status.conditions[?(@.type==\"Ready\")].reason" && echo "" && echo "" && oc get BaseUI -A -o custom-columns="KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,STATUS:status.conditions[?(@.type==\"Ready\")].reason" && echo "" && oc get AIManager,aiopsedge,asm -A -o custom-columns="KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,STATUS:status.phase"
NAMESPACE   NAME …
```
=> chore: Update WAIOps to 3.5

.releaserc, config/rhacm/cloudpaks/Chart.yaml, config/rhacm/cloudpaks/templates/placement-argocd.yaml
closes: #182
- Use "openshiftVersion" instead of "vendor=OpenShift" as a placement rule for Argo CD deployment
```
NAME                 CLUSTER                         NAMESPACE                PROJECT              STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                    TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops         default              Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd …
```
=> fix: Argo CD placement rule

config/cloudpaks/cp4i/install-platform/templates/0200-platform-navigator.yaml
Fix license code for Platform Navigator in Cloud Pak for Integration.
contributes-to: #177
=> fix: Fix license code for Platform Navigator in Cloud Pak for Integration

README.md, tests/postbuild/gitops.sh
Contributes to: #191
- Missing update to README.md
- GitOps deployment not waiting long enough to declare deployment complete
=> fix: Update CP4D version in README to 4.6.1

config/cloudpaks/cp4waiops/install-aimgr/Chart.yaml, config/cloudpaks/cp4waiops/install-aimgr/templates/subscriptions/100-subscription.yaml, config/cloudpaks/cp4waiops/install-emgr/Chart.yaml, config/cloudpaks/cp4waiops/install-emgr/templates/resources/210-event-manager.yaml, config/cloudpaks/cp4waiops/install-emgr/templates/subscriptions/100-subscription.yaml, config/cloudpaks/cp4waiops/install-emgr/values.yaml, config/cloudpaks/cp4waiops/install-ia/Chart.yaml, config/cloudpaks/cp4waiops/install-ia/templates/subscriptions/100-subscription.yaml
closes: #222
- Updates to CR versions to match WAIOps 3.7.0 release
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                      TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                             222-cp4waiops-370
cp-shared-app …
```
=> feat: Updates to CR versions to match WAIOps 3.7.0 release

config/argocd-cloudpaks/cp-shared/Chart.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-app.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-operators-app.yaml, config/argocd-cloudpaks/cp-shared/values.yaml, config/cloudpaks/cp-shared/operators/Chart.yaml, config/cloudpaks/cp-shared/operators/templates/0050-catalogsource-ibm.yaml, config/cloudpaks/cp-shared/operators/values.yaml
closes: #224
- Parameterize the priority of the online IBM operator catalog and default it to `-1`, eliminating the current collisions with other eventual IBM catalog sources added to the cluster from sources other than this repository.
=> feat: Reduce priority for ibm-operator-catalog catalog source

README.md, config/argocd-cloudpaks/cp4d/templates/0100-cp4d-app.yaml, config/argocd-cloudpaks/cp4d/templates/0200-cp4d-platform-app.yaml, config/argocd-cloudpaks/cp4d/values.yaml, config/cloudpaks/cp4d/Chart.yaml, config/cloudpaks/cp4d/templates/0100-sync-install-olm.yaml, config/cloudpaks/cp4d/templates/0100-sync-install-platform.yaml
closes: #227
- Update CP4D version to 4.6.4
- Parameterize location of common services
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                  TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                         227-cp4d-464 …
```
=> fix: Update Cloud Pak for Data to 4.6.4

config/argocd-cloudpaks/cp4d/templates/0010-argocd-role-binding-admin.yaml, docs/install.md
contributes-to: #193
- Fix instructions (they had the wrong target namespace for the Cloud Paks)
- Remove the "Replace" instruction from the offending CP4D RuleBinding mentioned in issue #193 
=> fix: UI-based installation instructions for Cloud Paks

config/cloudpaks/cp4waiops/install-aimgr/Chart.yaml, config/cloudpaks/cp4waiops/install-aimgr/templates/subscriptions/100-subscription.yaml, config/cloudpaks/cp4waiops/install-emgr/Chart.yaml, config/cloudpaks/cp4waiops/install-ia/Chart.yaml
Contributes to: #236 
- Upgrade CRs to match the WAIOps 3.7.1 release
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                      TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                             236-waiops-371 …
```
=> fix: Upgrade CP4WAIOps to 3.7.1

config/cloudpaks/cp4waiops/install-aimgr/Chart.yaml, config/cloudpaks/cp4waiops/install-emgr/Chart.yaml
closes: #241 
- Updates the version of WAIOps
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                      TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                             241-waiops-372
cp-shared-app        https://kubernetes.default.svc  ibm-cloudpaks     default …
```
=> fix: Update Cloud Pak for WAIOps 3.7.2

README.md, config/argocd-cloudpaks/cp-shared/Chart.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-common-service-maps.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-app.yaml, config/argocd-cloudpaks/cp-shared/values.yaml, docs/install.md, tests/postbuild/gitops.sh, tests/prebuild/yamllint-config.yaml
closes: #244 
- Make dedicated namespaces default to "false" (need more warning to adopters to adjust to the change)
=> fix: Parameterize the installation namespaces

config/argocd/templates/0200-argocd.yaml
closes: #245
- Enables OpenShift Dex integration.
=> feat: Enable OpenShift users to login to ArgoCD

config/cloudpaks/cp4d/Chart.yaml, config/cloudpaks/cp4d/templates/0090-sync-cluster-setup.yaml
closes: #249
- Avoid running cri-o tuning for Cloud Pak for Data in clusters using a hosted control plane.
From a self-managed AWS HCP cluster, notice how it notices that the cluster has a hosted control plane and does not apply the settings.
=> fix: Avoid running cri-o node setup for Cloud Pak for Data running on OCP with a hosted control plane

config/argocd-cloudpaks/cp-shared/Chart.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-common-config-map.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4a-config-map.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4s-config-map.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-app.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-operators-app.yaml, config/argocd-cloudpaks/cp-shared/values.yaml, config/argocd-cloudpaks/cp4i/Chart.yaml, config/argocd-cloudpaks/cp4i/templates/0301-cp4i-module-template-app.yaml, config/argocd-cloudpaks/cp4i/templates/0400-cp4i-client-app.yaml, config/argocd-cloudpaks/cp4i/values.yaml
closes: #276
- Uses string values for module selection in cp4i-app
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                    TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced     Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                           276-cp4i-boolean …
```
=> fix: Use strings for CP4I modules

config/argocd-cloudpaks/cp4i/Chart.yaml, config/argocd-cloudpaks/cp4i/templates/0100-cp4i-app.yaml, config/argocd-cloudpaks/cp4i/templates/0300-cp4i-platform-navigator.yaml, config/argocd-cloudpaks/cp4i/templates/0301-cp4i-module-template-app.yaml
contributes-to: #284
- Increase backoff duration for CP4I Applications
```
NAME                 CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                    TARGET
argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                           284-longer-sync …
```
=> fix: Increase backoff retries and duration for CP4I

config/argocd-cloudpaks/cp-shared/Chart.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-common-service-maps.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4s-config-map.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-app.yaml, config/argocd-cloudpaks/cp-shared/values.yaml, config/cloudpaks/cp4s/templates/resources/200-cp4s-threat-mgmt.yaml, docs/install.md
closes: #286
- Remove configuration for dedicated namespace for Cloud Pak for Data. It has native support for it.
- Remove configuration for dedicated namespace for Cloud Pak for Business Automation. It has native support for it.
- Remove configuration for dedicated namespace for Cloud Pak for AIOps. It does not support it.
=> fix: Remove dedicated ns for Data, BA, and AIOps

config/rhacm/seeds/Chart.yaml, config/rhacm/seeds/templates/0200-policy-openshift-gitops.yaml, docs/install.md, tests/descriptors/operators/gitops-operators.yaml
Closes: #288 
- Update operator version from `stable` to `gitops-1.8`
```
NAME                                  CLUSTER                         NAMESPACE                PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                  TARGET
openshift-gitops/argo-app             https://kubernetes.default.svc  openshift-gitops         argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                         288-ocp413
openshift-gitops/cp-shared-app …
```
=> chore: Update OpenShift GitOps to 1.8

README.md, config/cloudpaks/cp4aiops/install-aimgr/Chart.yaml, config/cloudpaks/cp4aiops/install-ia/Chart.yaml
closes: #292
- Updates Cloud Pak for AIOps to release 4.2.1
=> fix: Update AIOps to 4.2.1

config/argocd-rhacm/Chart.yaml, config/argocd-rhacm/templates/0000-app-project-rhacm-control-plane.yaml, config/argocd-rhacm/templates/0001-namespace-rhacm.yaml, config/argocd-rhacm/templates/0100-rhacm-app.yaml, config/argocd-rhacm/templates/0100-rhacm-seeds-app.yaml, config/argocd/Chart.yaml, config/argocd/templates/0010-app-project-argocd-control-plane.yaml, config/rhacm/seeds/Chart.yaml, docs/install.md, docs/rhacm.md
Contributes to: #294
- Includes RHACM control plane project in the rhacm-app
- Updates documentation to account for `argo-app` not being installed
```
NAME                              CLUSTER                         NAMESPACE                PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                    TARGET
openshift-gitops/argo-app         https://kubernetes.default.svc  openshift-gitops         argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd …
```
=> fix: Fix RHACM app project location

config/argocd/Chart.yaml, config/argocd/templates/0200-argocd.yaml, config/rhacm/seeds/Chart.yaml, config/rhacm/seeds/templates/0200-policy-openshift-gitops.yaml, docs/install.md, docs/rhacm.md, tests/descriptors/operators/gitops-operators.yaml, tests/postbuild/common.sh, tests/postbuild/gitops.sh
contributes-to: #289
- Modify ArgoCD configuration to use the new CRD design introduced in OpenShift GitOps 1.9.
**With OCP 4.12**
Installing CP4I as an example and validation that the custom health checks still work for its resources:
```
oc get csv 
NAME                                DISPLAY                    VERSION   REPLACES                           PHASE
openshift-gitops-operator.v1.10.1   Red Hat OpenShift GitOps   1.10.1    openshift-gitops-operator.v1.8.6   Succeeded
NAME                                  CLUSTER                         NAMESPACE         PROJECT               STATUS …
```
=> feat: Update OpenShift GitOps to 1.10

config/rhacm/seeds/Chart.yaml, config/rhacm/seeds/templates/0000-namespace-multi-cluster-engine.yaml, config/rhacm/seeds/templates/0100-rhacm-subscription.yaml, config/rhacm/seeds/templates/0200-gitops-managed-cluster-set.yaml, config/rhacm/seeds/templates/0301-managed-cluster-set-bindings.yaml, config/rhacm/seeds/templates/9000-post-multi-cluster-engine.yaml, docs/install.md, docs/rhacm.md, tests/prebuild/yamllint-config.yaml
closes: #297
- Upgrade RHACM subscription channel to 2.9
- Update links to RHACM and OCP documentation
- Update installation instructions
- Fix conditional creation of `multicluster-engine` namespace, as it should not be conditional
- Update API version for deprecated API groups
```
NAME                                  CLUSTER                         NAMESPACE                PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                  TARGET
openshift-gitops/argo-app             https://kubernetes.default.svc …
```
=> feat: Upgrade RHACM to 2.9

README.md, config/argocd-cloudpaks/cp4d/values.yaml, config/cloudpaks/cp4d/Chart.yaml, config/cloudpaks/cp4d/templates/0090-sync-cluster-setup.yaml, config/cloudpaks/cp4d/templates/0100-sync-install-olm.yaml, config/cloudpaks/cp4d/templates/0100-sync-install-platform.yaml, config/cloudpaks/cp4d/templates/0401-postsync-certificates.yaml, config/cloudpaks/cp4d/templates/0402-postsync-integrate-iam.yaml, config/cloudpaks/cp4d/values.yaml, docs/install.md
contributes-to: #300
- Follow CP4D install instructions and reflect changes in the corresponding areas of the repo
=> feat: Upgrade CP4D to 4.8.0

config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4a-config-map.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-app.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-operators-app.yaml, config/argocd-cloudpaks/cp-shared/values.yaml, config/argocd-cloudpaks/cp4a/Chart.yaml, config/argocd-cloudpaks/cp4a/templates/00-presync-adjust-prereq-config.yaml, config/argocd-cloudpaks/cp4a/templates/cp4a-app.yaml, config/argocd-cloudpaks/cp4a/templates/cp4a-operator-app.yaml, config/argocd-cloudpaks/cp4a/values.yaml, config/cloudpaks/cp-shared/operators/Chart.yaml, config/cloudpaks/cp-shared/operators/templates/0000-rh-cert-manager-namespace.yaml, config/cloudpaks/cp-shared/operators/templates/0100-rh-cert-manager-operator-group.yaml, config/cloudpaks/cp-shared/operators/templates/0110-rh-cert-manager-subscription.yaml, config/cloudpaks/cp-shared/operators/values.yaml, config/cloudpaks/cp4a/operators/templates/0050-sync-cluster-scoped-operators.yaml, config/cloudpaks/cp4a/operators/values.yaml, docs/install.md, tests/prebuild/yamllint-config.yaml
closes: #303
- Adds new red_hat_cert_manager parameter to `cp-shared` and `cp4a-app` applications and sub-applications.
- Adds conditional processing for adding either Red Hat Cert Manager or IBM Cert Manager depending on the value of the flag.
```
argocd app get cp4a-app --show-params
Name:               openshift-gitops/cp4a-app
Project:            default
Server:             https://kubernetes.default.svc
Namespace:          cp4a
URL:                https://openshift-gitops-server-openshift-gitops.apps.dncp4bacert.cp.fyre.ibm.com/applications/cp4a-app
Repo: …
```
=> feat: Support Red Hat Cert Manager

config/cloudpaks/cp4a/operators/templates/0050-sync-cluster-scoped-operators.yaml, config/cloudpaks/cp4a/operators/templates/0100-config-placeholder.yaml, config/cloudpaks/cp4a/operators/values.yaml, tests/postbuild/gitops.sh, tests/prebuild/yamllint-config.yaml
contributes-to: #303
- Deletes eventual IBM Cert Manager if Red Hat Cert Manager is enabled
(After manually setting the `red_hat_cert_manager` property in `cp-shared-app` and `cp4a-app` and synchronizing everything.) 
```
NAME                                  CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                  TARGET
openshift-gitops/argo-app             https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none> …
```
=> fix: Fix sync condition to cleanup IBM Cert Mgr

config/cloudpaks/cp4d/Chart.yaml, config/cloudpaks/cp4d/templates/0100-config-placeholder.yaml, config/cloudpaks/cp4d/templates/0100-sync-install-zen-workaround.yaml
closes: #304 
- Applies the patch of the technote listed in the issue: https://www.ibm.com/support/pages/node/7087504
Logs of the job execution:
```
+ result=1
+ '[' 1 -eq 1 ']'
+ '[' 0 -lt 7200 ']'
+ oc get deployment zen-databases -n cp4d-operands
W1208 13:37:21.615072       7 loader.go:222] Config not found: /opt/ansible/.kubeconfig
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
zen-databases   2/2     2            2           12h
+ result=0
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 0 ']'
+ oc patch deployment zen-databases -n cp4d-operands --type=json '-p=[{"op": "add", "path": …
```
=> fix: Patch Zen database for CP4D

config/argocd-cloudpaks/cp-shared/Chart.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-app.yaml, config/argocd-cloudpaks/cp-shared/templates/0100-cp-shared-operators-app.yaml, config/argocd-cloudpaks/cp-shared/values.yaml, config/cloudpaks/cp-shared/operators/Chart.yaml, config/cloudpaks/cp-shared/operators/templates/0050-sync-cluster-scoped-operators.yaml, config/cloudpaks/cp-shared/operators/templates/0100-rh-cert-manager-operator-group.yaml, config/cloudpaks/cp-shared/operators/templates/0110-rh-cert-manager-subscription.yaml, config/cloudpaks/cp-shared/operators/values.yaml, config/cloudpaks/cp4a/operators/values.yaml
closes: #313
- Parameterization of operator group for IBM Cert Manager
- Parameterization of operator group for Red Hat Cert Manager
- Delete unused parameters related to cert manager in cp4ba project.
```
NAME                                  CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                        PATH                                    TARGET
openshift-gitops/argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none> …
```
=> fix: Parameterize OperatorGroup for cert manager

config/argocd-cloudpaks/cp-shared/Chart.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-common-config-map.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-common-service-maps.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4a-config-map.yaml, config/argocd-cloudpaks/cp-shared/templates/0050-sync-cp4s-config-map.yaml, config/argocd-cloudpaks/cp4i/Chart.yaml, config/argocd-cloudpaks/cp4i/templates/0050-presync-adjust-app-config.yaml, config/argocd-cloudpaks/cp4i/templates/0310-sync-check-all-csvs.yaml, config/cloudpaks/cp-shared/operators/templates/0050-sync-cluster-scoped-operators.yaml, config/cloudpaks/cp4i/install-prereqs/templates/0050-sync-prereqs.yaml, tests/postbuild/gitops.sh
- Change sync hook classes from `quay.io/openshift/origin-cli:latest` to `registry.redhat.io/openshift4/ose-cli:latest`, which has support for multi-arch images.
- Account for `argocd` CLI having different download URLs depending on processor architecture
- Disable API Connect on Power architecture (not supported)
- Fixed bug in waiting for the IBM Cert Manager subscription
- Various updates to the `gitops.sh` script used to validate PRs, but most importantly, considering the different download URLs for the `argocd` CLI.
=> feat: Support Power processor architecture for CP4I deployment

config/argocd-cloudpaks/cp4a/Chart.yaml, config/argocd-cloudpaks/cp4a/templates/00-presync-adjust-prereq-config.yaml, config/argocd-cloudpaks/cp4a/templates/00-presync-adjust-storage-classes.yaml, config/cloudpaks/cp4a/operators/Chart.yaml, config/cloudpaks/cp4a/operators/templates/0100-presync-prereqs.yaml, config/cloudpaks/cp4a/operators/templates/0120-postsync-check-all-csvs.yaml, tests/postbuild/cluster.sh
- Change sync hook classes from `quay.io/openshift/origin-cli:latest` to `registry.redhat.io/openshift4/ose-cli:latest`, which has support for multi-arch images.
- Account for `argocd` CLI having different download URLs depending on processor architecture
=> feat: Support Power processor arch for CP4BA

config/argocd-cloudpaks/cp4s/templates/00-presync-adjust-parameters.yaml, config/cloudpaks/cp4s/templates/resources/100-sync-prereqs.yaml, config/cloudpaks/cp4s/templates/resources/220-openldap.yaml
- Use multi-arch images for sync hooks
Note the "OutOfSync" issue, related to an outstanding bug between the CP4S operator and the spec of the license field in the `CP4SThreatManagement` CR, which is expected until CP4S fixes the issue (see below, where the operator keeps removing the license field from one location and creating it in another location.)
```
NAME                                  CLUSTER                         NAMESPACE         PROJECT               STATUS     HEALTH   SYNCPOLICY  CONDITIONS  REPO …
```
=> chore: Use multi-arch image

config/cloudpaks/cp4aiops/install-aimgr/Chart.yaml, config/cloudpaks/cp4aiops/install-aimgr/templates/resources/000-presync-adjust-parameters.yaml, config/cloudpaks/cp4aiops/install-aimgr/templates/resources/230-postsync-certificates.yaml, config/cloudpaks/cp4aiops/install-aimgr/templates/subscriptions/030-sync-prereqs.yaml, config/cloudpaks/cp4aiops/install-aimgr/templates/subscriptions/110-sync-check-all-csvs.yaml, config/cloudpaks/cp4aiops/install-ia/Chart.yaml, config/cloudpaks/cp4aiops/install-ia/templates/resources/000-presync-adjust-parameters.yaml
- Use multi-arch images for Cloud Pak for AIOps
```
NAME                                  CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                     TARGET
openshift-gitops/argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd …
```
=> chore: Use multi-arch images for AIOps

config/argocd-cloudpaks/cp4d/Chart.yaml, config/argocd-cloudpaks/cp4d/templates/0000-presync-adjust-storage-classes.yaml, config/argocd-cloudpaks/cp4d/templates/0100-cp4d-app.yaml, config/argocd-cloudpaks/cp4d/templates/0200-cp4d-platform-app.yaml, config/argocd-cloudpaks/cp4d/values.yaml, config/cloudpaks/cp4d/Chart.yaml, config/cloudpaks/cp4d/templates/0090-sync-cluster-setup.yaml, config/cloudpaks/cp4d/templates/0100-sync-install-olm.yaml, config/cloudpaks/cp4d/templates/0100-sync-install-platform.yaml, config/cloudpaks/cp4d/templates/0100-sync-install-zen-workaround.yaml, config/cloudpaks/cp4d/templates/0401-postsync-certificates.yaml, config/cloudpaks/cp4d/templates/0402-postsync-integrate-iam.yaml
- Use multi-arch images in argo cd sync hooks
```
argocd app list -l app.kubernetes.io/instance=cp4d-app
NAME                            CLUSTER                         NAMESPACE         PROJECT  STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                          TARGET
openshift-gitops/cp4d-app       https://kubernetes.default.svc  openshift-gitops  default  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd-cloudpaks/cp4d  315-power-cp4d …
```
=> chore: Use multi-arch images for CP4D

config/rhacm/seeds/templates/0200-policy-openshift-gitops.yaml, docs/install.md, docs/rhacm.md, tests/descriptors/operators/gitops-operators.yaml
closes: #311
- Uses `latest` release of GitOps instead of a fixed release.
=> fix: Update GitOps operator to latest

README.md, config/cloudpaks/cp4a/operators/Chart.yaml, config/cloudpaks/cp4a/operators/templates/0000-catalog-sources.yaml, config/cloudpaks/cp4a/operators/templates/0110-base-operator.yaml, config/cloudpaks/cp4a/resources/Chart.yaml, config/cloudpaks/cp4a/resources/templates/0201-icp4a-cluster.yaml, config/cloudpaks/cp4a/resources/values.yaml
closes: #318 
- Update subscription and operator versions
- Use new option to use private CatalogSources (better for coexistence with other Cloud Paks)
```
NAME                                  CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                  TARGET
openshift-gitops/argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd …
```
=> fix: Update CP4BA to 23.0.2 ifix 1

config/cloudpaks/cp4s/Chart.yaml, config/cloudpaks/cp4s/templates/resources/200-cp4s-threat-mgmt.yaml
contributes-to: #271
- Updated CP4SThreatManagement to V2
```
NAME                                  CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                  TARGET
openshift-gitops/argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                         271-cp4s-v2
openshift-gitops/cp-shared-app …
```
=> chore: Update to CP4S 1.10.19

.github/workflows/close-pr.yml, .github/workflows/lint.yml, .github/workflows/test-pr.yml, README.md, config/cloudpaks/cp-shared/operators/Chart.yaml, config/cloudpaks/cp-shared/operators/templates/0050-sync-cluster-scoped-operators.yaml, config/cloudpaks/cp-shared/operators/values.yaml, config/cloudpaks/cp4aiops/install-aimgr/Chart.yaml, config/cloudpaks/cp4aiops/install-aimgr/templates/resources/200-ai-manager.yaml, config/cloudpaks/cp4aiops/install-aimgr/templates/subscriptions/100-subscription.yaml, config/cloudpaks/cp4aiops/install-aimgr/values.yaml, config/cloudpaks/cp4aiops/install-ia/Chart.yaml, config/cloudpaks/cp4aiops/install-ia/templates/subscriptions/100-subscription.yaml, tests/postbuild/cluster.sh
closes: #326
- Updates subscription channels
- Add installation of license manager
- Default test pipeline to OCP 4.14 (upgrade from OCP 4.12)
```
argocd app get cp4aiops-app
2024-02-06T22:15:55+0000: INFO: Synchronization of cp4aiops-app complete.
Name:               openshift-gitops/cp4aiops-app
Project:            default
Server:             https://kubernetes.default.svc/
Namespace:          cp4aiops
URL:                https://openshift-gitops-server-openshift-gitops.gitops-326-aiops-440-1e3af63cfd19e855098d645120e18baf-0000.us-south.containers.appdomain.cloud/applications/cp4aiops-app
Repo: …
```
=> feat: Upgrade Cloud Pak for AIOps to 4.4.0

docs/rhacm.md
Added missing --helm-set repoURL line so that it works if you add your own repo. The argo cd app and rhacm_control plane worked without this variable but if I used the base IBM/cloudpak-gitops/ repo but I was getting permissions error if I tried to install from my "slipsibm/cloudpak-gitops" repo
Contributes to: #332 
-added line for --helm-set repoURL
- <change 2 ... >
=> Update rhacm.md add --helm-set repoURL on argoCD-control-plane create

config/cloudpaks/cp-shared/operators/templates/0050-catalog-source-foundation-services.yaml, config/cloudpaks/cp4i/install-mq/Chart.yaml, config/cloudpaks/cp4i/install-mq/templates/0050-catalog-source-mq.yaml, config/cloudpaks/cp4i/install-mq/templates/0100-subscription-mq.yaml, config/cloudpaks/cp4i/install-mq/templates/0210-queue-manager.yaml, config/cloudpaks/cp4i/install-platform/Chart.yaml, config/cloudpaks/cp4i/install-platform/templates/0050-catalog-source-platform-navigator.yaml, config/cloudpaks/cp4i/install-prereqs/Chart.yaml, config/cloudpaks/cp4i/install-prereqs/values.yaml
closes: #334
- Update CatalogSources
- Update Subscriptions
- Update Operands
```
NAME                                  CLUSTER                         NAMESPACE         PROJECT               STATUS  HEALTH   SYNCPOLICY  CONDITIONS  REPO                                    PATH                                    TARGET
openshift-gitops/argo-app             https://kubernetes.default.svc  openshift-gitops  argocd-control-plane  Synced  Healthy  Auto-Prune  <none>      https://github.com/IBM/cloudpak-gitops  config/argocd                           main
openshift-gitops/cp-shared-app …
```
=> fix: Update CP4I 2023.4.1 versions

config/argocd/Chart.yaml, config/argocd/templates/0200-argocd.yaml, tests/postbuild/gitops.sh
closes: #100 
- Use instructions from Red Hat to make the ArgoCD server use the public cluster route: https://access.redhat.com/solutions/6041341
=> feat: Make ArgoCD use cluster cert
